### ISSUE TITLE
DH.derive_key uses SHA1, which is deprecated

### ISSUE THREAD

**Issue by UnixJunkie** [xavierleroy/cryptokit#19]
As a European citizen, I would prefer RIPEMD160, but I am not a specialist of those things.

**Comment by UnixJunkie** [comment]
A specialist advises SHA256:
https://crypto.stackexchange.com/questions/957/ripemd-versus-sha-x-what-are-the-main-pros-and-cons

**Comment by xavierleroy** [comment]
Fixed by #20 .

**Comment by UnixJunkie** [comment]
Thanks for your responsiveness.
Maybe a new minor release (a git tag) is in order, so that the opam package can be updated.
I know that a fix related to zlib was included recently.
