### ISSUE TITLE
Take symmetric key of any length

### ISSUE THREAD

**Issue by ethanxuyizhou** [xavierleroy/cryptokit#23]
I've only checked this for AES, and the key that [Cipher.aes] takes in is required to be of length 32. It would be great if it can take in string of any length.

**Comment by xavierleroy** [comment]
As the documentation says, Cipher.aes accepts keys of length 16, 24, or 32, corresponding to the standards AES-128, AES-192, and AES-256.  For each cipher, the documentation states the supported key sizes.

I think it would be dangerous for basic primitives like AES to silently truncate or pad keys to one of the standard key sizes.  It would make it too easy to get the key size wrong and end up with weak encryption.

If you need to derive keys from a string of arbitrary length, such as a password, you could use a hash function such as SHA-2 (remember to add salt!) or, much better, a key derivation algorithm such as [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2).

**Comment by UnixJunkie** [comment]
Having a KDF in cryptokit would be nice.
https://github.com/xavierleroy/cryptokit/issues/15
I thought someone had send a PR for one but can't find it back.
