### ISSUE TITLE
in ocp-browser, the ocamldoc showing for Cryptokit.hash_channel is the one for hash_string

### ISSUE THREAD

**Issue by UnixJunkie** [xavierleroy/cryptokit#3]
I have opam pinned cryptokit to the master git branch.
I don't know where this problem comes from.
I checked the related ocamldoc string, it looks correct.
I wonder if other users experience that too.

**Comment by UnixJunkie** [comment]
@dbuenzli you might have an idea. I think there is a bug somewhere and it is documentation related.

**Comment by UnixJunkie** [comment]
I have ocp-index.1.1.5 and ocaml 4.04.1.

**Comment by UnixJunkie** [comment]
I think versions of ocp-index that were shipping with older compilers like 4.01.0 were not affected.

**Comment by dbuenzli** [comment]
I think there's a doc string attachement problem [here](https://github.com/xavierleroy/cryptokit/blob/8895c61c75e30b95ed9b475e4f7bb0151d8d89d8/src/cryptokit.mli#L195-L208) in `cryptokit.mli`, a newline is needed. The rules became stricter when https://github.com/ocaml/ocaml/pull/149 was pulled in.

**Comment by xavierleroy** [comment]
Fixed in commit [master 8ba4083].  Thanks @dbuenzli for debugging this issue.
