### ISSUE TITLE
no opam file at the root of the source tree

### ISSUE THREAD

**Issue by UnixJunkie** [xavierleroy/cryptokit#9]
I will send a PR.
It allows opam users to pin the corresponding package to the HEAD of the source if needed
(for example, when you want to be sure if a bug is also in the HEAD of the version control).

**Comment by UnixJunkie** [comment]
https://github.com/xavierleroy/cryptokit/pull/10

**Comment by xavierleroy** [comment]
Now that we're using Dune, the .opam file is automatically generated.
